### ISSUE TITLE
pretty printed changes should align values

### ISSUE THREAD

**Issue by stevendborrelli** [asteris-llc/converge#244]
the changes output arrows should line up. Currently they are staggered:

```
root/file.file1:
    Messages:
    Has Changes: yes
    Changes:
        content:
        before:
            
        after:
            this is a test
            of the content module
            
        gid: "" => "20"
        group: "" => "staff"
        type: "" => "file"
        uid: "" => "501"
        username: "" => "steve"
```

This is a minor issue, but reformat output so that `=>` arrows line up.
